name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    # Run at 8 AM KST (23:00 UTC previous day)
    - cron: '0 23 * * *'
    # Run at 1 PM KST (04:00 UTC)
    - cron: '0 4 * * *'
    # Run at 6 PM KST (09:00 UTC)
    - cron: '0 9 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install pandas requests pyproj

      - name: Run matching_stn_info.py
        run: python matching_stn_info.py

      - name: Run get_more_stn_info.py
        run: python get_more_stn_info.py
        env:
          OPINET_API_KEY: ${{ secrets.OPINET_API_KEY }}

      - name: Run generate_gjssoil_data.py
        run: python generate_gjssoil_data.py
        env:
          OPINET_API_KEY: ${{ secrets.OPINET_API_KEY }}

      - name: Replace API keys
        run: |
          sed -i "s|appkey=YOUR_KAKAO_API_KEY|appkey=${{ secrets.KAKAO_API_KEY }}|g" index.html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .